name: sshnp_register_tool
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  at_client: ^3.0.40
  at_onboarding_cli: ^1.1.2
  at_utils: ^3.0.11
