name: at_commons
description: at_commons library will be used for commonly used components in implementation of the @protocol.
version: 1.0.1+6
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_process: ^1.0.5
