name: at_commons
description: A library of Dart and Flutter utility classes that are used across other components of the @â€Žplatform.
version: 3.0.12
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
  test_process: ^2.0.0
