name: at_ve_doctor
description: A sample command-line application.
publish_to: none
version: 1.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_server_status:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_server_status
      ref: null_safety
      version: 0.2.0

#dependency_overrides:
#  at_server_status:
#    path: ../../at_libraries/at_server_status

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
