name: at_cram
description: A command-line utility to generate CRAM digest
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.5

dependencies:
  args: ^2.3.1
